- hosts: localhost
  become: no
  vars:
    homebrew:
      repositories:
        - caskroom/fonts
        - neovim/neovim
      packages:
        - tmux
        - peco
        - ghq
        - neovim
        - reattach-to-user-namespace
        - plantuml
        - sbt
        - node
        - yarn
        - python
        - python3
      cask_packages:
        - virtualbox
        - virtualbox-extension-pack
        - docker-toolbox
        - font-nyashi
        - google-chrome
        # - karabiner

    anyenv:
      - env_name: rbenv
        environment: {}
        versions:
          - 2.1.2
          - 2.3.0
        global: 2.3.0
      - env_name: goenv
        environment: {}
        versions:
          - 1.6
        global: 1.6
      - env_name: ndenv
        environment: {}
        versions:
          - v5.11.0
        global: system
      - env_name: pyenv
        environment: {}
        versions:
          - miniconda3-3.19.0
        global: system
      - env_name: scalaenv
        environment: {}
        versions:
          - scala-2.11.8
        global: scala-2.11.8

  roles:
    - { role: homebrew, tags: [ 'mac' ] }
    - { role: terminal, tags: [ 'mac' ] }
    - anyenv
    # - { role: keymappings, tags: [ 'mac'] }
