[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'vim-scripts/matchit.zip'

[[plugins]]
repo = 'vim-scripts/netrw.vim'

[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'puppetlabs/puppet-syntax-vim'

[[plugins]]
repo = 'scrooloose/syntastic'
hook_source = 'source ~/.dotfiles/config/nvim/plugins/plugins/syntastic.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-unimpaired'
